# Generated by Django 4.2.7 on 2023-11-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overall_Quality', models.IntegerField()),
                ('Ground_Living_Sqft', models.IntegerField()),
                ('Garage_Car_Capacity', models.IntegerField()),
                ('Garage_Sqft', models.IntegerField()),
                ('Basement_Sqft', models.IntegerField()),
                ('First_Floor_Sqft', models.IntegerField()),
                ('Full_Baths', models.IntegerField()),
                ('Bedroom_Count', models.IntegerField()),
                ('Year_Built', models.IntegerField()),
                ('Year_Remodeled', models.IntegerField()),
            ],
        ),
    ]
